apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Values.appName}}-app-config"
  namespace: {{.Values.global.namespace}}
data:
  CONNECTION_STRING: {{.Values.connectionString}}
  JWT_SECRET: {{.Values.global.jwtSecret}}
  ADMIN_PASSWORD: {{.Values.adminPassword}}
