apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: {{.Values.global.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: 8080
          env:
          - name: CONNECTION_STRING
            valueFrom:
            secretKeyRef:
              name: floorball-fantasy
              key: USERS_CONNECTION_STRING
          - name: ADMIN_PASSWORD
            valueFrom:
            secretKeyRef:
              name: floorball-fantasy
              key: ADMIN_PASSWORD
          - name: JWT_SECRET
            valueFrom:
            secretKeyRef:
              name: floorball-fantasy
              key: JWT_SECRET
