helm:
  parameters:
  - name: users.image
    value: anzeha/ffantasy.users
    forcestring: true
  - name: users.tag
    value: staging-28b4249
    forcestring: true
  - name: squads.image
    value: anzeha/ffantasy.squads
    forcestring: true
  - name: squads.tag
    value: staging-0a58eca
    forcestring: true
  - name: frontend.image
    value: anzeha/ffantasy.web
    forcestring: true
  - name: frontend.tag
    value: staging-0bbe09f
    forcestring: true
  - name: gameweek-processor.image
    value: anzeha/ffantasy.gameweek-processor
    forcestring: true
  - name: gameweek-processor.tag
    value: staging-39e5c2e
    forcestring: true
  - name: game-domain.image
    value: anzeha/ffantasy.domain
    forcestring: true
  - name: game-domain.tag
    value: 457fd3a
    forcestring: true
