helm:
  parameters:
  - name: users.image
    value: anzeha/ffantasy.users
    forcestring: true
  - name: users.tag
    value: develop-89c9d66
    forcestring: true
  - name: squads.image
    value: anzeha/ffantasy.squads
    forcestring: true
  - name: squads.tag
    value: develop-89c9d66
    forcestring: true
  - name: frontend.image
    value: anzeha/ffantasy.web
    forcestring: true
  - name: frontend.tag
    value: develop-89c9d66
    forcestring: true
  - name: gameweek-processor.image
    value: anzeha/ffantasy.gameweek-processor
    forcestring: true
  - name: gameweek-processor.tag
    value: develop-89c9d66
    forcestring: true
  - name: game-domain.image
    value: anzeha/ffantasy.domain
    forcestring: true
  - name: game-domain.tag
    value: develop-89c9d66
    forcestring: true
