apiVersion: apps/v1
kind: Deployment
metadata:
  name: squads
  namespace: {{.Values.global.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squads
  template:
    metadata:
      labels:
        app: squads
    spec:
      containers:
        - name: squads
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: "{{.Values.appName}}-app-config"
