global:
  appName: floorball-fantasy
  namespace: floorball-fantasy-staging
  env: staging
  gameDomainServiceUrl: http://game-domain/
  usersServiceUrl: http://users/api/v1/
  squadsServiceUrl: http://squads/api/v1/
  elasticSearchUrl: http://esservice:9200
  hostname: staging-floorball-fantasy.duckdns.org



users:
  adminPassword: Password1!
# squads:
# OVERRIDE
#

# game-domain:
# OVERRIDE
