global:
  appName: floorball-fantasy
  namespace: floorball-fantasy-dev
  env: dev
  gameDomainServiceUrl: http://game-domain/
  usersServiceUrl: http://users/api/v1/
  squadsServiceUrl: http://squads/api/v1/
  jwtSecret: GNN/KHkBmyc3zKKQYLZW3Lv8W35t/6dfi4uRRrJI7QKbymFKn4Xs24viQDo+zn1/
  elasticSearchUrl: http://esservice:9200
  hostname: dev-floorball-fantasy.duckdns.org

database:
  dbUsername: test
  dbPassword: test

users:
  adminPassword: Password1!
  image: anzeha/ffantasy.users
  tag: develop-89c9d66
  
squads:
  image: anzeha/ffantasy.squads
  tag: develop-89c9d66


game-domain:
  image: anzeha/ffantasy.domain
  tag: develop-89c9d66

frontend:
  image: anzeha/ffantasy.web
  tag: develop-89c9d66

gameweek-processor:
  image: anzeha/ffantasy.gameweek-processor
  tag: develop-89c9d66
