global:
  appName: floorball-fantasy
  namespace: floorball-fantasy-dev
  env: dev
  gameDomainServiceUrl: http://game-domain
  usersServiceUrl: http://users
  squadsServiceUrl: http://squads
  jwtSecret: GNN/KHkBmyc3zKKQYLZW3Lv8W35t/6dfi4uRRrJI7QKbymFKn4Xs24viQDo+zn1/
  elasticSearchUrl: http://esservice:9200
  hostname: dev-floorball-fantasy.duckdns.org

database:
  dbUsername: test
  dbPassword: test

users:
  adminPassword: Password1!
  image: anzeha/ffantasy.users
  tag: 9bb6fa8
  
squads:
  image: anzeha/ffantasy.squads
  tag: 9bb6fa8


game-domain:
  image: anzeha/ffantasy.domain
  tag: 9bb6fa8

frontend:
  image: anzeha/ffantasy.web
  tag: 042db9c

gameweek-processor:
  image: anzeha/ffantasy.gameweek-processor
  tag: 457fd3a
