apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{.Values.global.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: 80
