apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{.Values.global.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: frontend
