apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{.Values.global.namespace}}-ingress-services"
  namespace: {{.Values.global.namespace}}
  labels:
    app.kubernetes.io/name: "{{.Values.global.namespace}}-ingress-services"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{.Values.global.hostname}}
      http:
        paths:
          - path: /users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: users
                port:
                  number: 80
          - path: /game-domain(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: game-domain
                port:
                  number: 80
          - path: /squads(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: squads
                port:
                  number: 80
          - path: /gameweek-processor(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gameweek-processor
                port:
                  number: 80
  ingressClassName: nginx
