apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: {{.Values.global.namespace}}
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1 
  template: 
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 4Gi
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"