apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: {{.Values.global.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
          ports:
            - containerPort: 9200
