apiVersion: v1
kind: Service
metadata:
  name: elastic
  namespace: {{.Values.global.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      protocol: TCP
  selector:
    app: elastic
