apiVersion: v1
kind: Service
metadata:
  name: esservice
  namespace: {{.Values.global.namespace}}
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200