apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-domain
  namespace: {{.Values.global.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-domain
  template:
    metadata:
      labels:
        app: game-domain
    spec:
      containers:
        - name: game-domain
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: "{{.Values.appName}}-app-config"
