apiVersion: v1
kind: Service
metadata:
  name: game-domain
  namespace: {{.Values.global.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: game-domain
